/*
 * File: leg_conv.c
 *
 * MATLAB Coder version            : 23.2
 * C/C++ source code generated on  : 17-Oct-2024 09:51:06
 */

/* Include Files */
#include "leg_conv.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_CONV
 *     T = LEG_CONV(F,Tp,PHI1,PHI4)
 *
 * Arguments    : float F
 *                float Tp
 *                float phi1
 *                float phi4
 *                float T[2]
 * Return Type  : void
 */
void leg_conv(float F, float Tp, float phi1, float phi4, float T[2])
{
  float t123_tmp;
  float t124_tmp;
  float t131_tmp;
  float t16_tmp;
  float t174;
  float t175;
  float t17_tmp;
  float t180_tmp;
  float t19_tmp;
  float t20_tmp;
  float t21_tmp;
  float t23_tmp;
  float t47_tmp;
  float t48_tmp;
  float t54_tmp;
  float t55_tmp;
  float t5_tmp;
  float t6_tmp;
  float t77_tmp;
  float t7_tmp;
  float t81_tmp;
  float t96;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2024-10-10 13:50:45 */
  t96 = cosf(phi1);
  t5_tmp = cosf(phi4);
  t6_tmp = sinf(phi1);
  t7_tmp = sinf(phi4);
  t16_tmp = t96 * 0.15F;
  t17_tmp = t5_tmp * 0.15F;
  t174 = t96 * 0.075F;
  t19_tmp = t5_tmp * 0.075F;
  t20_tmp = t6_tmp * 0.15F;
  t21_tmp = t7_tmp * 0.15F;
  t175 = t6_tmp * 0.075F;
  t23_tmp = t7_tmp * 0.075F;
  t47_tmp = t20_tmp - t21_tmp;
  t48_tmp = t175 - t23_tmp;
  t54_tmp = (t17_tmp - t16_tmp) + 0.125F;
  t55_tmp = (t19_tmp - t174) + 0.0625F;
  t77_tmp = t47_tmp * t47_tmp + t54_tmp * t54_tmp;
  t81_tmp = t96 * t47_tmp * 0.3F + t6_tmp * t54_tmp * 0.3F;
  t5_tmp = t5_tmp * t47_tmp * 0.3F + t7_tmp * t54_tmp * 0.3F;
  t7_tmp = 1.0F / (t55_tmp + t77_tmp);
  t47_tmp = t7_tmp * t7_tmp;
  t96 = sqrtf((t48_tmp * t48_tmp + t55_tmp * t55_tmp) - t77_tmp * t77_tmp);
  t54_tmp = 1.0F / t96;
  t96 += t23_tmp - t175;
  t6_tmp = atanf(t7_tmp * t96) * 2.0F;
  t123_tmp = cosf(t6_tmp);
  t124_tmp = sinf(t6_tmp);
  t131_tmp = 1.0F / (t47_tmp * (t96 * t96) + 1.0F);
  t6_tmp = t123_tmp / 4.0F;
  t180_tmp = (t175 + t81_tmp) * t47_tmp * t96 +
             t7_tmp * (t174 - t54_tmp *
                                  ((t16_tmp * t48_tmp + t20_tmp * t55_tmp) -
                                   t77_tmp * t81_tmp * 2.0F) /
                                  2.0F);
  t17_tmp = (t23_tmp + t5_tmp) * t47_tmp * t96 +
            t7_tmp * (t19_tmp - t54_tmp *
                                    ((t17_tmp * t48_tmp + t21_tmp * t55_tmp) -
                                     t77_tmp * t5_tmp * 2.0F) /
                                    2.0F);
  t19_tmp = t20_tmp + t124_tmp / 4.0F;
  t21_tmp = (t16_tmp + t6_tmp) - 0.0625F;
  t96 = (-t16_tmp - t6_tmp) + 0.0625F;
  t174 = t96 * t96;
  t175 = 1.0F / t96;
  t6_tmp = t19_tmp * t19_tmp;
  t81_tmp = t123_tmp * t131_tmp;
  t54_tmp = t16_tmp - t81_tmp * t180_tmp / 2.0F;
  t47_tmp = t124_tmp * t131_tmp;
  t5_tmp = t20_tmp - t47_tmp * t180_tmp / 2.0F;
  t7_tmp = F * (1.0F / sqrtf(t6_tmp + t21_tmp * t21_tmp));
  t6_tmp = Tp * t174 * (1.0F / (t6_tmp + t174));
  t96 = t19_tmp * (1.0F / t174);
  T[0] = t7_tmp * (t19_tmp * t54_tmp * 2.0F - t21_tmp * t5_tmp * 2.0F) / 2.0F -
         t6_tmp * (t175 * t54_tmp - t96 * t5_tmp);
  T[1] = t7_tmp * (t81_tmp * t19_tmp * t17_tmp - t47_tmp * t21_tmp * t17_tmp) /
             2.0F +
         t6_tmp * (t175 * (0.0F - t81_tmp * t17_tmp / 2.0F) +
                   t96 * (t47_tmp * t17_tmp / 2.0F));
}

/*
 * File trailer for leg_conv.c
 *
 * [EOF]
 */
