/*
 * File: leg_pos.c
 *
 * MATLAB Coder version            : 23.2
 * C/C++ source code generated on  : 17-Oct-2024 09:51:06
 */

/* Include Files */
#include "leg_pos.h"
#include "rt_nonfinite.h"
#include "rt_defines.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static float rt_atan2f_snf(float u0, float u1);

/* Function Definitions */
/*
 * Arguments    : float u0
 *                float u1
 * Return Type  : float
 */
static float rt_atan2f_snf(float u0, float u1)
{
  float y;
  if (rtIsNaNF(u0) || rtIsNaNF(u1)) {
    y = rtNaNF;
  } else if (rtIsInfF(u0) && rtIsInfF(u1)) {
    int i;
    int i1;
    if (u0 > 0.0F) {
      i = 1;
    } else {
      i = -1;
    }
    if (u1 > 0.0F) {
      i1 = 1;
    } else {
      i1 = -1;
    }
    y = atan2f((float)i, (float)i1);
  } else if (u1 == 0.0F) {
    if (u0 > 0.0F) {
      y = RT_PIF / 2.0F;
    } else if (u0 < 0.0F) {
      y = -(RT_PIF / 2.0F);
    } else {
      y = 0.0F;
    }
  } else {
    y = atan2f(u0, u1);
  }
  return y;
}

/*
 * LEG_POS
 *     POS = LEG_POS(PHI1,PHI4)
 *
 * Arguments    : float phi1
 *                float phi4
 *                float pos[2]
 * Return Type  : void
 */
void leg_pos(float phi1, float phi4, float pos[2])
{
  float a;
  float b_a;
  float t10;
  float t12;
  float t13;
  float t2;
  float t3;
  float t4;
  float t5;
  float t6;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2024-10-10 13:50:43 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t6 = t2 * 0.15F;
  t10 = t4 * 0.15F;
  t12 = t4 * 0.075F;
  t13 = t5 * 0.075F;
  t5 = t10 - t5 * 0.15F;
  a = t12 - t13;
  b_a = (t3 * 0.15F - t6) + 0.125F;
  t4 = (t3 * 0.075F - t2 * 0.075F) + 0.0625F;
  t5 = t5 * t5 + b_a * b_a;
  t4 = atanf(1.0F / (t4 + t5) *
             ((t13 - t12) + sqrtf((a * a + t4 * t4) - t5 * t5))) *
       2.0F;
  t5 = t10 + sinf(t4) / 4.0F;
  t4 = (t6 + cosf(t4) / 4.0F) - 0.0625F;
  pos[0] = sqrtf(t5 * t5 + t4 * t4);
  pos[1] = rt_atan2f_snf(t5, t4);
}

/*
 * File trailer for leg_pos.c
 *
 * [EOF]
 */
